### ISSUE TITLE
experiment_cardinal.py available?

### ISSUE THREAD

**Issue by remcinerney** [nextml/caption-contest-data#6]
Is the experiment_cardinal.py file and YAML file for the New Yorker experiments available?
I'm just trying to ensure that Ive understood how you configure the experiments...

**Comment by stsievert** [comment]
The YAML file should be at "examples/cartoon_cardinal/init.yaml". This provides complete configuration for the experiment; experiment_cardinal really only reads in this file and hits a certain endpoint.

I feel that doesn't answer your question though; why are you looking for how the experiments are launched?

If you'd like to be added to our Slack channel, send me an email at scott@stsievert.

**Comment by remcinerney** [comment]
Sending you an email now!

**Comment by liamim** [comment]
Closing because it's stale and was handled out-of-band.
